### ISSUE TITLE
How do you obtain the data of ClimaX?

### ISSUE THREAD

**Issue by Hank0626** [Aalto-QuML/ClimODE#3]
The RMSE data reported in your paper is:

![截屏2024-05-24 13 17 36](https://github.com/Aalto-QuML/ClimODE/assets/77595899/e7e952b1-2423-463b-9e52-fa09cf1fba89)

However, the RMSE data in the original [ClimaX](https://arxiv.org/abs/2301.10343) paper is:
![截屏2024-05-24 13 18 35](https://github.com/Aalto-QuML/ClimODE/assets/77595899/6f5f138a-27af-43a4-9b01-379c08127dde)

For instance, in our paper, the RMSE of u10 for a 72-hour lead time is stated as 3.70, whereas in the ClimaX paper, it is reported as 2.18. Could you provide clarification on this inconsistency?

**Comment by yogeshverma1998** [comment]
Hi,

ClimaX training incorporates two parts: (i) Pre-training and (ii) Fine-tuning. The pre-training is done on historical CMIP6 data, and the resulting model is fine-tuned on the ERA5 dataset. Our study does not use any pertaining data, and we utilize a fixed number of observables (See Appendix B). Thus, for a fair comparison, direct comparison is not viable.

To obtain a fair comparison, we run the climax model without pre-training (with the exact set of hyper-parameters as provided in the official repo) and utilize the same data splits we use to train ClimODE.

**Comment by Hank0626** [comment]
In the fine-tuning phase, climaX uses more than 5 variables as input. climaX used 41 variables from era5 as input and 5 as output.  So, you train climaX from scratch (without fine-tuning) using only 5 variables as input the same as output and get results?

**Comment by yogeshverma1998** [comment]
Due to academic computational constraints, we only utilize those 5 variables for all our experiments. To have a fair comparison, we train climax on these 5 variables (without any pre-training) and using the same set of hyper-parameters provided in their repo.

**Comment by Hank0626** [comment]
ok, tks!

**Comment by tung-nd** [comment]
ClimaX was proposed as a foundation model for climate science. When we say ClimaX, we always refer to the pretrained model. The architecture itself without pretraining is not ClimaX, it is just a normal ViT. Moreover, the hyperparameters used for training ClimaX should not be the same as the ones used for finetuning a pretrained model. Please update your paper to clarify this, and the baseline you're comparing to should be pure ViT, not ClimaX.
