### ISSUE TITLE
CRPS scale

### ISSUE THREAD

**Issue by JimengShi** [Aalto-QuML/ClimODE#4]
Hi folks, congrats to your amazing work.

Is it possible to provide the scale of CRPS scores for different variables? Figure 5 clearly shows `Z` CRPS scores range from 0 to 0.025. What about other variables? Are these 5 variables within the scale? Thanks!

**Comment by yogeshverma1998** [comment]
Hi, 

The scale (y-axis) in Fig 5 is shared among all the variables.

**Comment by yogeshverma1998** [comment]
Hi,

Due to inactivity, I assume the issue has been resolved and am closing it. If you have any other questions, feel free to open another issue.
